# Generated by Django 5.1.6 on 2025-02-20 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('estimated_diameter', models.FloatField()),
                ('close_approach_date', models.DateField()),
                ('velocity', models.FloatField()),
                ('distance_from_earth', models.FloatField()),
                ('is_hazardous', models.BooleanField()),
            ],
            options={
                'db_table': 'asteroids',
            },
        ),
        migrations.CreateModel(
            name='Tracked_asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traked_at', models.DateTimeField(auto_now_add=True)),
                ('asteroid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asteroids.asteroid')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'tracked_asteroids',
            },
        ),
    ]
