# Generated by Django 5.1.6 on 2025-02-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite_images',
            old_name='astronomical_images_id',
            new_name='astronomical_images',
        ),
        migrations.RenameField(
            model_name='favourite_images',
            old_name='user_id',
            new_name='user',
        ),
    ]
